baseURL = "http://localhost:1313"
disableLanguages = []
disqusShortname = "themefisher-template"
googleAnalytics = ""
paginate = "6"
summaryLength = "10"
theme = "reader-hugo"
title = "Reader | Hugo Personal Blog Template"
[imaging]
quality = 100
[markup.goldmark.extensions]
footnote = true
[markup.goldmark.renderer]
unsafe = true
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
