[en]
contentDir = "content/english"
heading = "What Would You <br> Like To Read Today?"
languageCode = "en-us"
languageName = "En"
weight = 1
[en.about_me]
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet . Libero ullamcorper."
image = "/images/lindsay-paige-rush.jpg"
title = "Hi, I am Alex!"
[fr]
contentDir = "content/french"
heading = "Qu'aimeriez-vous <br> lire aujourd'hui?"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[fr.about_me]
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet . Libero ullamcorper."
image = "images/author.jpg"
title = "Hi, I am Alex!"
