[en]
contentDir = "content/english"
heading = ""
languageCode = "en-us"
languageName = "En"
weight = 1
[en.about_me]
bio = "Hey there! I am a copywriter with in-house and agency experience developing and delivering creative content. I'm passionate about telling stories, exploring audience insights and crafting memorable messaging. Committed to the creative process, I enjoy bringing ideas to life. "
image = "images/lindsay-paige-rush.png"
title = "Lindsay Paige Rush"
[fr]
contentDir = "content/french"
heading = "Qu'aimeriez-vous <br> lire aujourd'hui?"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[fr.about_me]
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet . Libero ullamcorper."
image = "images/lindsay-paige-rush.png"
title = "Hi, I am Alex!"
