[[footer]]
URL = "privacy-policy/"
name = "Privacy Policy"
weight = 1
[[footer]]
URL = "terms-conditions/"
name = "Terms Conditions"
weight = 2
[[main]]
hasChildren = true
name = "homepage"
weight = 1
[[main]]
hasChildren = false
name = "Homepage Minimal"
parent = "homepage"
url = "homepage/minimal/"
weight = 1
[[main]]
hasChildren = false
name = "Homepage Full Width"
parent = "homepage"
url = "homepage/full/"
weight = 2
[[main]]
hasChildren = false
name = "Homepage Full With Left Sidebar"
parent = "homepage"
url = "homepage/full-left/"
weight = 3
[[main]]
hasChildren = false
name = "Homepage Full With Right Sidebar"
parent = "homepage"
url = "homepage/full-right/"
weight = 4
[[main]]
hasChildren = false
name = "Homepage List Style"
parent = "homepage"
url = "homepage/list/"
weight = 5
[[main]]
hasChildren = false
name = "Homepage List With Left Sidebar"
parent = "homepage"
url = "homepage/list-left/"
weight = 6
[[main]]
hasChildren = false
name = "Homepage List With Right Sidebar"
parent = "homepage"
url = "homepage/list-right/"
weight = 7
[[main]]
hasChildren = false
name = "Homepage Grid Style"
parent = "homepage"
url = "homepage/grid/"
weight = 8
[[main]]
hasChildren = false
name = "Homepage Grid With Left Sidebar"
parent = "homepage"
url = "homepage/grid-left/"
weight = 9
[[main]]
hasChildren = false
name = "Homepage Grid With Right Sidebar"
parent = "homepage"
url = "homepage/grid-right/"
weight = 10
[[main]]
URL = "#"
hasChildren = false
name = "About"
weight = 2
[[main]]
hasChildren = false
name = "About Me"
parent = "About"
url = "about-me/"
weight = 1
[[main]]
hasChildren = false
name = "About Us"
parent = "About"
url = "about-us/"
weight = 2
[[main]]
URL = "contact/"
hasChildren = false
name = "Contact"
weight = 3
[[main]]
hasChildren = true
name = "Pages"
weight = 4
[[main]]
hasChildren = false
name = "Author"
parent = "Pages"
url = "author/"
weight = 1
[[main]]
hasChildren = false
name = "Category"
parent = "Pages"
url = "categories/creativity/"
weight = 2
[[main]]
hasChildren = false
name = "Tags"
parent = "Pages"
url = "tags/food/"
weight = 3
[[main]]
hasChildren = false
name = "404 Page"
parent = "Pages"
url = "404/"
weight = 4
