author = "Lindsay"
banner = false
contact_form_action = "#"
custom_script = ""
description = "This is meta description"
favicon = "images/favicon.png"
featured_post = false
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Reader"
logo_width = "100x"
main_taxonomy = "tag"
menu_align = "center"
post_layout = "full"
search = true
sidebar = "right"
[background_shapes]
banner_bg_image = "images/backgrounds/banner-bg.svg"
enable = true
footer_bg_image = "images/backgrounds/footer-bg.svg"
header_bg_image = "images/backgrounds/header-bg.svg"
wave_bg_image = "images/backgrounds/wave-bg.svg"
[cookies]
enable = false
expire_days = 2
[instafeed]
access_token = ""
enable = false
[preloader]
enable = false
preloader = ""
[promotion]
button_label = "Get Started"
button_link = "https://themefisher.com/"
content = "Lorem ipsum dolor sit amet, consectetur sociis. Etiam nunc amet id dignissim. Feugiat id tempor vel sit ornare."
image = "images/promotion.jpg"
title = "Create Stunning Website!!"
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["search", "authors", "social", "tags", "recent-post", "categories", "about-me", "promotion", "subscription"]
[[social]]
icon = "fab fa-linkedin-in"
link = "#"
name = "linkedin"
[[social]]
icon = "far fa-envelope"
link = "/contact"
name = "Email"
