baseURL = "http:localhost:1313/"
theme = "the-real-lindsay"
title = "Lindsay Paige Rush | Writing Portfolio"
description = "The Writing Portfolio of professional marketer, copywriter, storyteller & brand strategist Lindsay Paige Rush"
author = "Lindsay Paige Rush"
