---
new_page_extension: md
auto_deploy: false
admin_path: "/editor"
webhook_url: 
sections:
- type: document
  path: data/portfolio/intro.yaml
  label: Portfolio Intro Content
  match: "**/*"
- type: directory
  path: data/portfolio/items
  label: Portfolio Items
  create: documents
  match: "**/*"
  new_doc_ext: ".yaml"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.93.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
