---
label: Config
hide_body: true
fields:
- type: text
  name: baseURL
  label: baseURL
- type: text
  name: title
  label: title
- type: text
  name: theme
  label: theme
- type: text
  name: paginate
  label: paginate
- type: text
  name: summaryLength
  label: summaryLength
- type: text
  name: googleAnalytics
  label: googleAnalytics
- type: text
  name: disqusShortname
  label: disqusShortname
- type: list
  name: disableLanguages
  label: disableLanguages
- type: field_group
  name: imaging
  label: imaging
  fields:
  - type: number
    name: quality
    label: quality
- type: field_group
  name: outputs
  label: outputs
  fields:
  - type: list
    name: home
    label: home
- type: field_group
  name: markup
  label: markup
  fields:
  - type: field_group
    name: goldmark
    label: goldmark
    fields:
    - type: field_group
      name: renderer
      label: renderer
      fields:
      - type: boolean
        name: unsafe
        label: unsafe
    - type: field_group
      name: extensions
      label: extensions
      fields:
      - type: boolean
        name: footnote
        label: footnote
- type: field_group
  name: mediaTypes
  label: mediaTypes
  fields:
  - type: field_group
    name: application/manifest+json
    label: application/manifest+json
    fields:
    - type: list
      name: suffixes
      label: suffixes
  - type: field_group
    name: text/netlify
    label: text/netlify
    fields:
    - type: text
      name: delimiter
      label: delimiter
    - type: list
      name: suffixes
      label: suffixes
- type: field_group
  name: outputFormats
  label: outputFormats
  fields:
  - type: field_group
    name: WebAppManifest
    label: WebAppManifest
    fields:
    - type: text
      name: mediaType
      label: mediaType
    - type: text
      name: rel
      label: rel
