---
label: Config
hide_body: true
fields:
- type: text
  name: baseURL
  label: Website URL
- type: text
  name: title
  label: Website Title
- type: text
  name: theme
  label: theme
  hidden: true
- type: text
  name: paginate
  label: Pagination
  description: How many pages deep do you want to display content on the Home?
- type: text
  name: summaryLength
  label: Summary Length
  description: How long of a summary do you want to pull into each item?
- type: text
  name: googleAnalytics
  label: Google Analytics
  description: Paste in the ID for your Google Analytics account. It'll be something
    like UA-12345-67
- type: text
  name: disqusShortname
  label: disqusShortname
  hidden: true
- type: list
  name: disableLanguages
  label: disableLanguages
  config:
    use_select: false
    source:
      type: simple
  hidden: true
- type: field_group
  name: imaging
  label: imaging
  fields:
  - type: number
    name: quality
    label: quality
    hidden: true
  hidden: true
- type: field_group
  name: outputs
  label: outputs
  fields:
  - type: list
    name: home
    label: home
    hidden: true
  hidden: true
- type: field_group
  name: markup
  label: markup
  fields:
  - type: field_group
    name: goldmark
    label: goldmark
    fields:
    - type: field_group
      name: renderer
      label: renderer
      fields:
      - type: boolean
        name: unsafe
        label: unsafe
        hidden: true
      hidden: true
    - type: field_group
      name: extensions
      label: extensions
      fields:
      - type: boolean
        name: footnote
        label: footnote
        hidden: true
      hidden: true
    hidden: true
  hidden: true
- type: field_group
  name: mediaTypes
  label: mediaTypes
  fields:
  - type: field_group
    name: application/manifest+json
    label: application/manifest+json
    fields:
    - type: list
      name: suffixes
      label: suffixes
      hidden: true
    hidden: true
  - type: field_group
    name: text/netlify
    label: text/netlify
    fields:
    - type: text
      name: delimiter
      label: delimiter
      hidden: true
    - type: list
      name: suffixes
      label: suffixes
      hidden: true
    hidden: true
- type: field_group
  name: outputFormats
  label: outputFormats
  fields:
  - type: field_group
    name: WebAppManifest
    label: WebAppManifest
    fields:
    - type: text
      name: mediaType
      label: mediaType
      hidden: true
    - type: text
      name: rel
      label: rel
      hidden: true
    hidden: true
  hidden: true
pages:
- config/_default/config.toml
