######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/reader/"
title = "Reader | Hugo Personal Blog Template"
theme = "reader-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

# Image Processing Config
[imaging]
quality = 100


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[markup]
[markup.goldmark.renderer]
unsafe= true
[markup.goldmark.extensions]
footnote= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"