################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
heading = "What Would You <br> Like To Read Today?"

[en.about_me]
title = "Hi, I am Alex!"
image = "images/author.jpg"
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet . Libero ullamcorper."


################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
heading = "Qu'aimeriez-vous <br> lire aujourd'hui?"

[fr.about_me]
title = "Hi, I am Alex!"
image = "images/author.jpg"
bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vel in in donec iaculis tempus odio nunc laoreet . Libero ullamcorper."